### ISSUE TITLE
Перевести формы регистрации, авторизации и шаблоны e-mail'ов на русский язык

### ISSUE THREAD

**Issue by Matvey-Kuk** [Matvey-Kuk/makers_against_covid#2]

**Comment by hom3chuk** [comment]
@Matvey-Kuk не шарю в джанге, но хоть с этим могу помочь. Тут какой-то i18n или прям в шаблонах шпарить перевод?

**Comment by Matvey-Kuk** [comment]
@hom3chuk можно прям в шаблонах, удалять оттуда i18n. Если дойдем до перевода, заново расставим все теги по шаблонам

**Comment by Farelkin** [comment]
#26 готово

**Comment by Matvey-Kuk** [comment]
@Farelkin ❤️
