### ISSUE TITLE
Более подробные карточки изделий

### ISSUE THREAD

**Issue by SmallSharky** [Matvey-Kuk/makers_against_covid#7]
- Фотографии изделия
- Текстовое описание
- Габариты одного изделия (X,Y,Z)
- Какой тип принтеров способен напечатать изделие
- Сложность изделия (насколько сложно напечатать)

**Comment by Matvey-Kuk** [comment]
Я только за, буду очень рад, если кто-то их оформит. Дубль #3

**Comment by Matvey-Kuk** [comment]
Открою, т.к. здесь есть описание

**Comment by Matvey-Kuk** [comment]
Информация для всех: 

Изделия можно добавить pull request'ом сюда: https://github.com/Matvey-Kuk/makers_against_covid/tree/master/mac/apps/orders/templates/products

И сюда: https://github.com/Matvey-Kuk/makers_against_covid/blob/master/mac/apps/orders/models.py#L13

**Comment by SmallSharky** [comment]
Нет. Не так. В функционале сайта.

**Comment by Matvey-Kuk** [comment]
Изделий с десяток, можно для экономии времени разработчиков и ради ревью через pr, принимать их в виде статики

**Comment by Matvey-Kuk** [comment]
Из московского чатика (https://t.me/cvd_msk_3dprint): https://drive.google.com/drive/folders/1qzgSXqIe0xUsjVlpivS35IqXKiO1BLzY

**Comment by musinit** [comment]
https://github.com/Matvey-Kuk/makers_against_covid/pull/24
